name: pandoc_ebook

on: 
  workflow_dispatch:
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    #env: 
    #  working-directory: ./ebook/cancer_screening
    steps:
      - uses: actions/checkout@master
      - run: cd ebook/cancer_screening/
      - run: ls ebook/cancer_screening/
      - run: mkdir output
      - uses: maxheld83/pandoc-action@v2
        with:
          args: --output=output/test.md "ebook/cancer_screening/000-intro.md ebook/cancer_screening/001-colorectal.md"
