name: pandoc_ebook

on: 
  workflow_dispatch:
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    #env: 
    #  working-directory: ./ebook/cancer_screening
    steps:
      #- run: cd ebook/cancer_screening/
      - run: dir github/workspace
      - uses: docker://pandoc/core:2.9
        with:
          args: "/github/workspace/ebook/cancer_screening/000-intro.md /github/workspace/ebook/cancer_screening/001-colorectal.md > /github/workspace/ebook/cancer_screening/test.md"
