name: pandoc_ebook

on: 
  workflow_dispatch:
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    env: 
      working-directory: ./ebook/cancer_screening
    steps:
      #- run: cd ebook/cancer_screening/
      - run: dir
      - uses: docker://pandoc/core:2.9
        with:
          args: "000-intro.md 001-colorectal.md > test.md"
