name: pandoc_ebook

on: 
  workflow_dispatch:
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    #env: 
    #  working-directory: ./ebook/cancer_screening
    steps:
      #- run: cd ebook/cancer_screening/
      - run: echo ls
