name: pandoc_ebook

on: 
  workflow_dispatch:
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    #env: 
    #  working-directory: ./ebook/cancer_screening
    steps:
      - uses: actions/checkout@master
      - run: cd ebook/cancer_screening/
      - run: ls ebook/cancer_screening/
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --output=ebook/cancer_screening/test.md
            ebook/cancer_screening/000-intro.md
            ebook/cancer_screening/001-colorectal.md
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add ebook
      - run: git commit -m "action update"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
