
name: pandoc_ebook

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: cd ebook/cancer_screening/
      - run: dir
      - uses: docker://pandoc/core:2.9
        with:
          args: "*.md"
