name: pandoc_ebook

on: 
  workflow_dispatch:
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    #env: 
    #  working-directory: ./ebook/cancer_screening
    steps:
      - uses: actions/checkout@master
      - run: echo ls
